# =====================================================
# PROFILE: DEV (ch?y local v?i STS/IntelliJ/cmd)
# =====================================================
spring.kafka.bootstrap-servers=localhost:29092

app.keycloak.url=http://localhost:8180

logging.level.com.booking=DEBUG