
  # =========================
  # Kafka
  # =========================
spring.kafka.bootstrap-servers=localhost:29092

  # =========================
  # Keycloak
  # =========================
app.keycloak.url=http://localhost:8180

  # =========================
  # Logging
  # =========================
logging.level.com.booking=DEBUG
logging.level.org.hibernate=WARN
logging.level.org.springframework=WARN

