<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.booking</groupId>
    <artifactId>booking-system</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>booking-system</name>
    <description>SmartBooking multi-module backend aggregator</description>

    <modules>
        <module>api-gateway</module>
        <module>auth-service</module>
        <module>booking-service</module>
        <module>camunda-service</module>
        <module>payment-service</module>
        <module>keycloak-provider</module>
    </modules>
</project>
