#Application
spring.application.name=api-gateway
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

#Spring Cloud Compatibility
spring.cloud.compatibility-verifier.enabled=false

#Server
server.port=8080
server.netty.max-header-size=65536

#Routes
# AUTH_SERVICE_URL: localhost:8081 (dev) ho?c auth-service:8081 (docker)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=admin-service
spring.cloud.gateway.routes[1].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/admin/**

# Route: Internal (Keycloak verify)
spring.cloud.gateway.routes[2].id=internal-service
spring.cloud.gateway.routes[2].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/internal/**

#CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=${ALLOWED_ORIGINS:http://localhost:4200}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

#Actuator
management.endpoints.web.exposure.include=health,info


logging.level.com.booking.gateway=INFO

# Route: Tickets (User)
spring.cloud.gateway.routes[3].id=ticket-service
spring.cloud.gateway.routes[3].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/tickets/**

# Route: Profile (User)
spring.cloud.gateway.routes[4].id=profile-service
spring.cloud.gateway.routes[4].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/users/**