# Docker profile overrides
spring.datasource.url=jdbc:postgresql://postgres:5432/booking_db?currentSchema=payment
spring.datasource.username=booking_user
spring.datasource.password=BookingPass@2024

spring.data.redis.host=redis
spring.data.redis.password=RedisPass@2024

spring.kafka.bootstrap-servers=kafka:9092